name: workflow

on:
  push:
  schedule:
    - cron: '0 0 * * 1'  # run every Monday

jobs:
  workflow:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Initialisation
      uses: actions/checkout@v2

    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: conda-environment
        environment-file: .github/environment.yml

    - name: Install package
      run: python -m pip install .[dev]

    - name: Unit tests
      env:
        PYTEST_ADDOPTS: "--color=yes"
      run: invoke test.unittest
      if: matrix.os != 'ubuntu-latest'

    - name: Unit tests with coverage
      env:
        PYTEST_ADDOPTS: "--color=yes"
      run: invoke test.coverage
      if: matrix.os == 'ubuntu-latest'

    - name: Documentation tests
      env:
        PYTEST_ADDOPTS: "--color=yes"
      run: invoke test.docs

    - name: Jupyter notebook tests
      env:
        PYTEST_ADDOPTS: "--color=yes"
      run: invoke test.ipynb

    - name: Upload coverage to Codecov.io
      uses: codecov/codecov-action@v1
      if: matrix.os == 'ubuntu-latest'
